import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <header className="bg-black text-white p-4">
          <nav className="flex justify-between">
            <Link href="/" className="text-lg">E-Commerce</Link>
            <div>
              <Link href="/cart" className="mx-4">Cart</Link>
              <Link href="/favorites">Favorites</Link>
            </div>
          </nav>
        </header>
        <div className="bg-zinc-100 container mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
